version: '3'

volumes:
  consailapi_dev_postgres_data: {}
  consailapi_dev_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/dev/django/Dockerfile
    image: consailapi_dev_django
    container_name: consailapi_dev_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.dev/.django
      - ./.envs/.dev/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: consailapi_production_postgres
    container_name: consailapi_dev_postgres
    volumes:
      - consailapi_dev_postgres_data:/var/lib/postgresql/data:Z
      - consailapi_dev_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.dev/.postgres

  nginx:
    build:
      context: ./compose/dev/nginx/
      dockerfile: Dockerfile
    depends_on:
      - django
    volumes:
      - ./consailapi:/app/log/nginx
      - ./consailapi:/app/consailapi:z
    ports:
      - 80:80
    restart: on-failure

  redis:
    image: redis:6
    container_name: consailapi_dev_redis

  celeryworker:
    <<: *django
    image: consailapi_dev_celeryworker
    container_name: consailapi_dev_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: consailapi_dev_celerybeat
    container_name: consailapi_dev_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: consailapi_dev_flower
    container_name: consailapi_dev_flower
    ports:
      - "5555:5555"
    command: /start-flower
